### ISSUE TITLE
Cannot issue certificates

### ISSUE THREAD

**Issue by doloban** [CZERTAINLY/CZERTAINLY-Core#864]
Hello,
we have problems with issuing certificates through CZERTAINLY. CZERTAINLY version is 2.11 (planning to do upgrade soon), PYADCS connector has version 1.1.1. Everything seems to be configured fine, CZERTAINLY WinRM service account has permissions to issue certificates with the specific certificate template, issuing also works when trying to issue the specific certificate with WinRM service account on the CA server, but it doesnt work when the issue request occurs on the CZERTAINLY side. Is this problem fixed in the version 2.13 with the newer version of pyadcs connector, or is it different issue? The certificate template is active only on the one CA, which is connected to CZERTAINLY. Sending logs.
[issueerror.log](https://github.com/user-attachments/files/17255143/issueerror.log)

**Comment by jakub-moravek** [comment]
Hello Doloban,

Please, try to upgrade CZERTAINLY to the latest version first. There were some fixes in PyADCS connector. If the problem would still occur, could you check logs on MS ADCS side? Unfortunately, the CZERTAINLY logs do not provide much details.

    Jakub

**Comment by 3keyroman** [comment]
I am sure the issue here is with incompatibility of CZERTAINLY version 2.11 with PyADCS connector version 1.1.1.

We have introduced CRMF support in CZERTAINLY version 2.12 and the PyADCS support this from version 1.1.0. The request needs to identify the type of CSR and this will not be compatible with older versions of CZERTAINLY. And it will cause the mentioned issue.

Upgrate to current latest version 2.13 is recommended and it should work again.
